apiVersion: v1
kind: Service
metadata:
  labels:
    app: ubi
  name: ubi
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: ubi
  sessionAffinity: None
  type: ClusterIP