apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-test-appproject
  namespace: argo-test
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: argo-test
  destinations:
    - name: in-cluster
      namespace: openshift-gitops
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/gmeghnag/argo-test'
status: {}
